name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 18.x
      uses: actions/setup-node@v1
      with:
        node-version: 18.x
    - name: Install yarn
      run: npm install -g yarn
    - name: Bootstrap Script
      run: yarn
    - uses: actions/checkout@v2
      with:
        repository: microsoft/TypeScript
        path: ts
    - name: Bootstrap TypeScript
      run: npm install
      working-directory: ./ts
    - name: Rewrite TypeScript Config
      run: node ./src/rewrite.mjs ./ts
    - name: Build TypeScript
      run: npm run build
      working-directory: ./ts
    - name: Convert libs
      run: node ./src/convert.mjs ./ts/built/local -o ./libs/index.d.ts
    - name: Upload build
      uses: actions/upload-artifact@v4
      with:
        name: libs
        path: ./libs
